version: "3"

services:
  ghost:
    image: "ghost:5.74"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost-database
      database__connection__user: ghost
      database__connection__password: ghostpassword
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: production
    depends_on:
      - ghost-database


  ghost-proxy:
    image: ghostcms-web
    build: nginx
    ports:
      - "8080:80"

  ghost-database:
    image: "mysql:8.2"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpassword
    volumes:
      - ghost-database:/var/lib/mysql

volumes:
    ghost-database: